# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {} is {} kilometers." .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
d['k1'][3]["tricky"][3]['target'][3]

'hello'

# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [11]:
arr=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35:",arr)

Array of all the even integers from 20 to 35: [20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b),axis=None)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [14]:
import pandas as pd

In [15]:
data=[['A',10],['B',15],['C',20]]
df=pd.DataFrame(data,columns=['name','age'])
print(df)

  name  age
0    A   10
1    B   15
2    C   20


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [17]:
from datetime import date as date_n
def n_days(d1,d2):
    return(d2-d1).days
date_1 =dn(2023,1,1)
date_2 =date_n(2023,2,10)
print("Number of days between the given dates are:",number_of_days(date_1,date_2),"days")

Number of days between the given dates are: 40 days


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [18]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [19]:
df = pd.DataFrame(lists, columns = ['s.no' , 'name' , 'number'])
print(df)

   s.no name  number
0     1  aaa      22
1     2  bbb      25
2     3  ccc      24
